apiVersion: apps/v1
kind: Deployment
metadata:
  name: rededorserver
spec:
  selector:
    matchLabels:
      app: rededorserver
  replicas: 2
  template:
    metadata:
      labels:
        app: rededorserver
    spec:
      containers:
      - name: rededorserver
        image: parisivitor95/rededor:latest
        ports:
        - containerPort: 8000
