apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deplyment.yml
- servie.yml

images:
- name: rededorserver
  newName: parisivitor95/rededor
  newTag: a9c870135a6ce602f6ffd9930a1c2a7fd61c4c36
