apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deplyment.yml
- servie.yml

images:
- name: rededorserver
  newName: parisivitor95/rededor
  newTag: 98224ecb0918942f978c7a3ed46fb4633e19c777
