name: CD Gitops

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: ${{ secrets.GIT_USERNAME }}/rededor
        tags:  ${{ github.sha }}, latest

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: "5.3.0"

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image rededorserver=$DOCKER_USERNAME/rededor:$GITHUB_SHA

    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker version"

    - name: Push new tag name
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        repository: ${{ secrets.GIT_USERNAME }}/rededor
