name: CD Gitops

on:
  push:
    branches:
      - 'main'

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONA_ACCESS_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          parisivitor95/rededor:${{ github.sha }}
          parisivitor95/rededor:latest-prod
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: "5.3.0"

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image rededorserver=$DOCKER_USERNAME/rededor:$GITHUB_SHA

    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update Docker image tag to $GITHUB_SHA"
        git push origin main --force
    env:
        GITHUB_TOKEN: ${{ secrets.PERSONA_ACCESS_TOKEN }}

    # - name: create pull request
    #   run: gh pr create -B update-main -H main --title 'Update Docker image tag to $GITHUB_SHA' --body 'Created by Github action'
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push new tag name
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     repository: parisivitor/rededor
    #     branch: main
    #     force: true

    # - name: Commit
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     base_branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')  # Obtém o nome da branch atual
    #     git checkout -b "${base_branch}"
    #     git pull origin  "${base_branch}"

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v5
    #   with:
    #     branch: update-main
    #     base: main
    #     commit-message: "Release Update"
    #     title: "Release Update"
    #     labels: "auto-merge"
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PERSONA_ACCESS_TOKEN }}
