name: CD Gitops

on:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          parisivitor95/rededor:${{ github.sha }}
          parisivitor95/rededor:latest-prod
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: "5.3.0"

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image rededorserver=$DOCKER_USERNAME/rededor:$GITHUB_SHA

    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b update-main
        git commit -am "Update Docker image tag to $GITHUB_SHA"
        git push origin update-main
        hub pull-request -b main -h update-main -m "Release Update"

          env:
            GITHUB_TOKEN: ${{ secrets.PERSONA_ACCESS_TOKEN }}

    # - name: Push new tag name
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     repository: parisivitor/rededor
    #     branch: main
    #     force: "+refs/heads/main:refs/heads/main"
