name: ci-python-workflow

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        run: docker login ghcr.io -u parisivitor95@gmail.com -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ghcr.io/parisivitor95/rededor:latest
        env:
          DOCKER_USERNAME: parisivitor95@gmail.com
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Run tests in Docker container
        run: docker run parisivitor95/rededor:latest python -m unittest discover -s src/user/tests -p 'test_*.py'
