name: ci-python-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
        echo "PYTHONPATH=${GITHUB_WORKSPACE}/src/user" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s src/user/tests -p 'test_*.py'
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Set up Docker
    #     uses: docker/setup-qemu-action@v2

    #   - name: Set up QEMU
    #     uses: docker/setup-buildx-action@v1

    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: false

    #   - name: Run tests in Docker container
    #     run: |
    #       docker run my-python-app python -m unittest discover -s src/user/tests -p 'test_*.py'
