name: Release Workflow

on:
  push:
    branches:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/heads/release/})
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release Branch
        run: |
          git checkout -b "release/$VERSION"
          git push origin "release/$VERSION"

      - name: Trigger CD Workflow
        uses: actions/workflow-run-action@v2
        with:
          workflow: "CD Gitops"
          ref: "refs/heads/release/$VERSION"
